version: 2.1

orbs:
  node: circleci/node@5.0.0
  envsubst: sawadashota/envsubst@1.1.0
  docker: circleci/docker@2.0.3
  codecov: codecov/codecov@3.2.2

jobs:
  build:
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "--add-opens=java.prefs/java.util.prefs=ALL-UNNAMED -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dorg.gradle.parallel=true -Dorg.gradle.project.isCi=true"
    docker:
      - image: cimg/openjdk:17.0.1
    resource_class: medium
    steps:
      - checkout
      - node/install:
          node-version: "17.6.0"
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: Build
          command: ./gradlew build -x test -x check
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - persist_to_workspace:
          root: .
          paths:
            - build
  test:
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "--add-opens=java.prefs/java.util.prefs=ALL-UNNAMED -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dorg.gradle.parallel=true -Dorg.gradle.project.isCi=true"
    docker:
      - image: cimg/openjdk:17.0.1
    resource_class: medium
    steps:
      - checkout
      - node/install:
          node-version: "17.6.0"
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: ./gradlew test -x check
      - codecov/upload

  check:
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "--add-opens=java.prefs/java.util.prefs=ALL-UNNAMED -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dorg.gradle.parallel=true -Dorg.gradle.project.isCi=true"
    docker:
      - image: cimg/openjdk:17.0.1
    resource_class: medium
    steps:
      - checkout
      - node/install:
          node-version: "17.6.0"
      - attach_workspace:
          at: .
      - run:
          name: Run style validator
          command: ./gradlew check -x test

  docker-compose:
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "--add-opens=java.prefs/java.util.prefs=ALL-UNNAMED -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dorg.gradle.parallel=true -Dorg.gradle.project.isCi=true"
      GRPC_SERVER_PORT: 9090
      GRPC_PROXY_PORT: 8080
      ENVOY_ADMIN_PORT: 9091
      ENVOY_PROXY_ENDPOINT_ADDRESS: 0.0.0.0
      ENVOY_DOCKER_NETWORK_MODE: host
    machine:
      - image: cimg/openjdk:17.0.1
    resource_class: medium
    steps:
      - checkout
      - envsubst/install
      - docker/install-docker-compose
      - run: ./gradlew dockerComposeUp
      - run: ./gradlew dockerComposeDown

workflows:
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - check:
          requires:
            - build
      - docker-compose
