[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools ~= 62.4",
    "wheel"
]

[project]
name = "nnbuilder-python"
version = "0.0.0"
dependencies = [
    "numpy",
    "psycopg2",
    "torch",
    "json",
    "logging",
    "sklearn",
    "dotenv",
    "os",
    "pandas"
]

[project.scripts]
constructor = "constructor.train:train"
